### ISSUE TITLE
AWS Secrets YAML 

### ISSUE THREAD

**Issue by sauadwaya** [samos123/multi-cloud-messaging#2]
Thanks for your tutorial.

I am assuming in the aws-secrets.yaml file you have a AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for your account. How did you set up the permissions to publish to SNS though? Or does your credentials gives the GCP cloud function broad/admin privileges? 

I was thinking of setting up an IAM role that has permission to publish to SNS, and then assuming the credentials of that IAM role from the google cloud function, but not sure how to establish the trust relationship between the google cloud function entity and the IAM role.

**Comment by samos123** [comment]
I think you could use Federated Identity. Here is an example of how that would work with S3: https://cloud.google.com/storage-transfer/docs/source-amazon-s3#federated_identity (the same approach can probably be used for SNS)

I think  I used  environment variables to set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` and boto picks those up by default. See more on env variables here: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables
(it's been a long time and work at Google Cloud so haven't touched AWS since this demo)
